### ISSUE TITLE
Error when deleting description

### ISSUE THREAD

**Issue by MitarashiDangoCodes** [texterify/texterify#63] opened 2021-09-03 09:01 UTC
Deleting of description is not always working.
Error: 'Name is already in use'

Also the string is empty in Android Studio, despite the text is in the translation field

**Comment by chrztoph** [comment] 2021-09-03 09:28
Hey, can you provide a video or a screenshot what you are doing and where the error is shown? I'm not able to reproduce this issue.

This would help a lot.

**Comment by chrztoph** [comment] 2021-12-06 11:33
Closing this issue as I'm not able to reproduce this. We might have fixed this already due to other improvements and bug fixes we made. If you still experience this issue feel free to open a new issue and provide some more information so we can get this fixed.

Thank you! 🙂

**Closed by chrztoph** 2021-12-06 11:33 UTC
